name: Docker Build and Push

on:
  push:
    branches:
      - develop-circleci

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ 1998salman }}
        password: ${{ 2-D*S$Pb6@Lh4ve }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/your-repo-name:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/your-repo-name:${{ github.sha }}
